// ==UserScript==
// @name         Grepo_Apoio-Botao_Sentinela
// @namespace    Botao_Sentinela
// @author       BadUser
// @description  Adiciona um botao para sentinela
// @version      1.0.0
// @match        http://*.grepolis.com/game/*
// @match        https://*.grepolis.com/game/*
// ==/UserScript==

(function () {
    'use strict';
    const uw = unsafeWindow ? unsafeWindow : window;

    /* Retorna true se a pólis tiver suas próprias tropas dentro, caso contrário, ou se for a pólis do jogador */
    function possuiSentinela(id) {
        const cidades = Object.keys(uw.ITowns.towns);
        for (let cidade of cidades) {
            if (cidade == id) return true;
            const modelos = uw.ITowns.all_supporting_units.fragments[cidade].models;
            for (let modelo of modelos) if (modelo.attributes.current_town_id == id) return true;
        }
        return false;
    }

    /* Retorna true se a pólis estiver na ilha da pólis ativa atual */
    function estaNaIlhaAtual(x, y) {
        const cidadeAtual = uw.ITowns.getCurrentTown();
        const cx = cidadeAtual.getIslandCoordinateX();
        const cy = cidadeAtual.getIslandCoordinateY();
        if (cx == x && cy == y) return true;
        return false;
    }

    /* Faz uma requisição ajax */
    function enviarSentinela(unidade, id_alvo) {
        let dados = { id: id_alvo, tipo: 'apoio' };
        dados[unidade] = 1;
        uw.gpAjax.ajaxPost('town_info', 'send_units', dados);
    }

    /* Retorna qual unidade da pólis atual pode ser usada */
    function selecionarUnidade() {
        let unidades = uw.ITowns.getCurrentTown().getLandUnits();
        if (unidades.sword > 1) return 'sword';
        if (unidades.archer > 1) return 'archer';
        if (unidades.hoplite > 1) return 'hoplite';
        if (unidades.slinger > 1) return 'slinger';
        if (unidades.rider > 1) return 'rider';
        if (unidades.chariot > 1) return 'chariot';
        if (unidades.small_transporter > 1) return 'small_transporter';
        return null;
    }

    /* Retorna true se a pólis já tiver um suporte a caminho */
    function possuiSuporteChegando(id_alvo) {
        let movimentos = uw.MM.getModels().MovementsUnits;
        for (let m in movimentos) if (movimentos[m].attributes.target_town_id == id_alvo) return true;
        return false;
    }

    /* Lida com o clique do botão de sentinela no menu de contexto */
    function tratarCliqueNoBotao(alvo) {
        let unidade = selecionarUnidade();
        if (!unidade) {
            uw.HumanMessage.error('Nenhuma tropa disponível');
            return;
        }
        enviarSentinela(unidade, alvo.id);
    }

    /* Quando o usuário clica na pólis, define a pólis atual */
    uw.$.Observer(uw.GameEvents.map.town.click).subscribe((e, dados) => {
        if (!estaNaIlhaAtual(dados.x, dados.y)) return;
        if (possuiSentinela(dados.id)) return;
        if (possuiSuporteChegando(dados.id)) return;
        let menu = uw.$('#context_menu');
        if (!menu) return;
        let div = document.createElement('div');
        div.id = 'sentinel_button';
        div.style.width = '50px';
        div.style.height = '50px';
        div.style.position = 'absolute';
        div.style.background = `url(https://i.ibb.co/9wwBNfD/sentinel.png)`;
        div.style.zIndex = 'auto';
        div.style.cursor = 'pointer';
        div.innerHTML = `
        <div id="sentinel_description" style="position: absolute;overflow: hidden;width: 118px;display: none;margin-left: -59px;left: 50%;top: 40px;z-index: 5;" >
        <div style="position: absolute; top: 0; left: 0; right: 0; background: url(https://gpit.innogamescdn.com/images/game/autogenerated/layout/layout_095495a.png) no-repeat -488px -406px; width: 118px; height: 18px;"></div>
        <div style="position: absolute; top: 18px; left: 0; right: 0; bottom: 11px; background: url(https://gpit.innogamescdn.com/images/game/layout/context_menu_middle.png) repeat-y 0 0;"></div>
        <div style="position: absolute; bottom: 0; left: 0; right: 0; background: url(https://gpit.innogamescdn.com/images/game/autogenerated/layout/layout_095495a.png) no-repeat -326px -240px; width: 118px; height: 11px;"></div>
        <div style="color: #fc6; font-weight: 700; text-align: center; word-wrap: break-word; line-height: 19px; z-index: 1; position: relative; padding: 4px;">Sentinela</div>
        </div>`;
        menu.append(div);
        uw.$('#sentinel_button').animate({ top: '-100px' }, 120);
        uw.$('#sentinel_button').hover(
            () => {
                uw.$('#sentinel_description').css('display', 'block');
            },
            () => {
                uw.$('#sentinel_description').css('display', 'none');
            },
        );
        uw.$('#sentinel_button').click(() => {
            tratarCliqueNoBotao(dados);
            menu.remove();
        });
    });

    console.log('[Grepo_Apoio-Botao_Sentinela] Carregado');
})();
